import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export const runtime = "nodejs";

type RenderRequest = {
  hairstyleName: string;
  selfieBase64: string;
  mimeType: string;
};

function getClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not set");
  }
  return new GoogleGenerativeAI(apiKey);
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as RenderRequest;

    if (!body.selfieBase64 || !body.hairstyleName) {
      return NextResponse.json(
        { error: "Missing selfie or hairstyle name." },
        { status: 400 }
      );
    }

    const client = getClient();

    const model = client.getGenerativeModel({
      // Image-capable Gemini model for edits / generations.
      model: "gemini-1.5-flash",
    });

    const prompt = `
You are a professional virtual hairstylist.
Take this exact person and render them with the hairstyle described below.
Keep their identity, skin tone, and general lighting the same, but convincingly change only the hair.

Hairstyle to apply: "${body.hairstyleName}"
`.trim();

    const result = await model.generateContent({
      contents: [
        {
          role: "user",
          parts: [
            { text: prompt },
            {
              inlineData: {
                data: body.selfieBase64,
                mimeType: body.mimeType || "image/jpeg",
              },
            },
          ],
        },
      ],
      generationConfig: {
        responseMimeType: "image/png",
      },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);

    const candidates = result.response.candidates;
    const parts = candidates?.[0]?.content?.parts || [];

    const imagePart = parts.find(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (p: any) => p.inlineData && p.inlineData.data
    ) as { inlineData?: { data: string } } | undefined;

    if (!imagePart?.inlineData?.data) {
      return NextResponse.json(
        { error: "No image generated by Gemini." },
        { status: 500 }
      );
    }

    // Return a data URL so the frontend can drop it straight into an <img />.
    const dataUrl = `data:image/png;base64,${imagePart.inlineData.data}`;

    return NextResponse.json({ image: dataUrl });
  } catch (error) {
    console.error("Error in /api/render-hairstyle:", error);
    return NextResponse.json(
      { error: "Failed to render hairstyle image." },
      { status: 500 }
    );
  }
}

